### ISSUE TITLE
Graphic Design

### ISSUE THREAD

**Issue by nunojesus** [amirsaranBIH/open-polls#1]
I think this project is a great idea, so I would like to contribute with something, so as a graphic designer I could design a logo if you want.

Greetings and congrats for this project.

**Comment by nunojesus** [comment]
Yes I have: Nuno Jesus#3231

**Comment by nunojesus** [comment]
![logo blue](https://user-images.githubusercontent.com/34600369/40010266-206e1416-579c-11e8-9753-db7bb00e63a8.png)

I create this that are the letter O and P, see if you like it.

**Comment by amirsaranBIH** [comment]
It's great. Do you make website designs?

**Comment by nunojesus** [comment]
I make that too, but for that I have to have time, at the moment I dont have it, but what do you want?

**Comment by nunojesus** [comment]
For the logo do you want me to create the png files ? Is it good for you? What colors do you want?

**Comment by nunojesus** [comment]
![oplogo-model2](https://user-images.githubusercontent.com/34600369/40228655-c33c8fac-5a89-11e8-927d-17712637f01d.png)
